name: Upload plugin to GCS
run-name: Upload plugin to GCS - ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  gcs:
    environment: testing
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_GH_TESTING }}
          service_account: wp-omnisend-ci@omnisend-testing-251206.iam.gserviceaccount.com

      - name: 'install-zip'
        run: sudo apt-get update && sudo apt-get install zip -y

      - id: 'zip-plugin'
        run: ./zip_plugin.sh test

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'omnisend-test.zip'
          destination: 'omnisend_testing_woocommerce'
