name: Omniguard Scan
run-name: Omniguard Scan ${{ github.head_ref || github.ref_name }}

on:
  workflow_dispatch:

jobs:
  omniguard-scan:
    name: Omniguard Scan
    permissions:
      contents: read
      issues: write
    uses: omnisend/omniguard-cli/.github/workflows/omniguard-scan.yml@master
    secrets: inherit
