name: Omniguard Check Root Issue

on:
  issues:
    types: [closed]

jobs:
  check-root-issue:
    name: Omniguard Check Root Issue
    permissions:
      issues: write
    uses: omnisend/omniguard-cli/.github/workflows/omniguard-check-root-issue.yml@master
    secrets: inherit
